In [1]:
import cv2
import numpy as np
img = cv2.imread("messi5.jpg")

In [2]:
px = img[100,100]
print(px)

[157 166 200]


In [3]:
blue = img[100,100,0]
print(blue)

157


In [6]:
img[100,100] = [255, 255, 255]
print(img[100,100])

[255 255 255]


In [7]:
img.item(10,10,2)

59

In [8]:
img.itemset((10,10,2),100)
img.item(10,10,2)

100

In [9]:
print(img.shape)

(342, 548, 3)


In [10]:
print(img.size)

562248


In [11]:
print(img.dtype)

uint8


In [12]:
ball = img[280:340, 330:390]
img[273:333, 100:160] = ball

In [13]:
print(img[273:333, 100:160])

[[[ 57 147 101]
  [ 55 147 100]
  [ 56 147 102]
  ...
  [ 54 147 102]
  [ 56 147 102]
  [ 55 146 101]]

 [[ 64 149 104]
  [ 61 149 103]
  [ 59 148 104]
  ...
  [ 54 147 102]
  [ 56 147 102]
  [ 55 146 101]]

 [[ 60 149 105]
  [ 61 150 106]
  [ 61 150 106]
  ...
  [ 57 148 103]
  [ 57 148 103]
  [ 57 148 103]]

 ...

 [[ 51 127  86]
  [ 63 141 100]
  [ 43 122  81]
  ...
  [ 40 116  74]
  [ 44 118  76]
  [ 62 136  94]]

 [[ 38 116  75]
  [ 56 135  94]
  [ 50 129  88]
  ...
  [ 57 137  94]
  [ 73 151 110]
  [ 66 144 103]]

 [[ 83 161 120]
  [ 64 146 104]
  [ 78 160 118]
  ...
  [ 60 145 101]
  [ 57 139  97]
  [ 56 135  94]]]


In [14]:
b, g, r= cv2.split(img)
img = cv2.merge((b,g,r))

In [15]:
img

array([[[ 39,  43,  44],
        [ 42,  46,  47],
        [ 44,  47,  52],
        ...,
        [ 57,  55,  55],
        [ 55,  53,  53],
        [ 52,  50,  50]],

       [[ 37,  40,  44],
        [ 42,  45,  49],
        [ 46,  49,  54],
        ...,
        [ 62,  60,  60],
        [ 60,  58,  58],
        [ 57,  55,  55]],

       [[ 41,  45,  50],
        [ 46,  50,  55],
        [ 51,  55,  60],
        ...,
        [ 64,  63,  65],
        [ 63,  62,  64],
        [ 60,  59,  61]],

       ...,

       [[ 56, 143,  99],
        [ 48, 133,  89],
        [ 49, 129,  86],
        ...,
        [ 60, 134,  92],
        [ 63, 134,  94],
        [ 73, 145, 103]],

       [[ 54, 138,  96],
        [ 59, 141,  99],
        [ 50, 130,  87],
        ...,
        [ 56, 132,  91],
        [ 69, 142, 104],
        [ 64, 137,  97]],

       [[ 45, 129,  87],
        [ 58, 140,  98],
        [ 71, 151, 108],
        ...,
        [ 49, 124,  86],
        [ 52, 125,  87],
        [ 51, 124,  86]]

In [16]:
b = img[:,:,0]

In [17]:
b

array([[39, 42, 44, ..., 57, 55, 52],
       [37, 42, 46, ..., 62, 60, 57],
       [41, 46, 51, ..., 64, 63, 60],
       ...,
       [56, 48, 49, ..., 60, 63, 73],
       [54, 59, 50, ..., 56, 69, 64],
       [45, 58, 71, ..., 49, 52, 51]], dtype=uint8)

In [18]:
img[:,:,2] = 0