In [1]:
#Erosion
import cv2
import numpy as np
img = cv2.imread("j.png",0)
kernel = np.ones((5,5),np.uint8)
erosion = cv2.erode(img,kernel,iterations=1)
cv2.imshow("img",img)
cv2.imshow("erosion",erosion)
k = cv2.waitKey(0)
if k == ord("q"):
    cv2.destroyAllWindows()

In [2]:
#dilation
import cv2
import numpy as np
img = cv2.imread("j.png",0)
kernel = np.ones((5,5),np.uint8)
dilation = cv2.dilate(img,kernel,iterations=1)
cv2.imshow("img",img)
cv2.imshow("dilation",dilation)
k = cv2.waitKey(0)
if k == ord("q"):
    cv2.destroyAllWindows()

In [3]:
#opening
import cv2
import numpy as np
img = cv2.imread("noisej.jpg",0)
kernel = np.ones((5,5),np.uint8)
opening = cv2.morphologyEx(img,cv2.MORPH_OPEN,kernel)
cv2.imshow("img",img)
cv2.imshow("opening",opening)
k = cv2.waitKey(0)
if k == ord("q"):
    cv2.destroyAllWindows()

In [4]:
#closing 
import cv2
import numpy as np
img = cv2.imread("noisej1.jpg",0)
kernel = np.ones((5,5),np.uint8)
closing = cv2.morphologyEx(img,cv2.MORPH_CLOSE,kernel)
cv2.imshow("img",img)
cv2.imshow("closing",closing)
k = cv2.waitKey(0)
if k == ord("q"):
    cv2.destroyAllWindows()

In [5]:
#morphological gradient
import cv2
import numpy as np
img = cv2.imread("m_gradient.jpg",0)
kernel = np.ones((5,5),np.uint8)
m_gradient = cv2.morphologyEx(img,cv2.MORPH_GRADIENT,kernel)
cv2.imshow("img",img)
cv2.imshow("m_gradient",m_gradient)
k = cv2.waitKey(0)
if k == ord("q"):
    cv2.destroyAllWindows()

In [7]:
#top_hat
#opening
import cv2
import numpy as np
img = cv2.imread("tophat.jpg",0)
kernel = np.ones((9,9),np.uint8)
tophat = cv2.morphologyEx(img,cv2.MORPH_TOPHAT,kernel)
cv2.imshow("img",img)
cv2.imshow("opening",tophat)
k = cv2.waitKey(0)
if k == ord("q"):
    cv2.destroyAllWindows()

In [8]:
#black_hat
import cv2
import numpy as np
img = cv2.imread("blackhat.jpg",0)
kernel = np.ones((5,5),np.uint8)
black_hat = cv2.morphologyEx(img,cv2.MORPH_BLACKHAT,kernel)
cv2.imshow("img",img)
cv2.imshow("opening",black_hat)
k = cv2.waitKey(0)
if k == ord("q"):
    cv2.destroyAllWindows()

In [9]:
cv2.getStructuringElement(cv2.MORPH_RECT,(5,5))

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]], dtype=uint8)

In [10]:
cv2.getStructuringElement(cv2.MORPH_ELLIPSE,(5,5))

array([[0, 0, 1, 0, 0],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [0, 0, 1, 0, 0]], dtype=uint8)

In [11]:
cv2.getStructuringElement(cv2.MORPH_CROSS,(5,5))

array([[0, 0, 1, 0, 0],
       [0, 0, 1, 0, 0],
       [1, 1, 1, 1, 1],
       [0, 0, 1, 0, 0],
       [0, 0, 1, 0, 0]], dtype=uint8)